[0m20:06:23.591645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000000005D37A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000000070A8700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000000007E433D0>]}


============================== 20:06:23.595645 | 4bf6e737-c650-4559-b2f6-5f21da39acf5 ==============================
[0m20:06:23.595645 [info ] [MainThread]: Running with dbt=1.10.5
[0m20:06:23.596645 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Administrator\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:06:33.668909 [debug] [MainThread]: Starter project path: C:\Users\Administrator\dbt_env\lib\site-packages\dbt\include\starter_project
[0m20:06:33.684178 [info ] [MainThread]: 
Your new dbt project "duckdbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:06:33.685220 [info ] [MainThread]: Setting up your profile.
[0m20:06:38.719727 [error] [MainThread]: Encountered an error:

[0m20:06:38.735130 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\cli\requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\cli\requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\cli\main.py", line 483, in init
    results = task.run()
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\task\init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "C:\Users\Administrator\dbt_env\lib\site-packages\dbt\task\init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "C:\Users\Administrator\dbt_env\lib\site-packages\click\termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "C:\Users\Administrator\dbt_env\lib\site-packages\click\termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:06:38.737132 [debug] [MainThread]: Command `dbt init` failed at 20:06:38.737132 after 15.21 seconds
[0m20:06:38.738133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000000005D37A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000000008014A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000000008016050>]}
[0m20:06:38.739132 [debug] [MainThread]: Flushing usage events
[0m20:06:39.502270 [debug] [MainThread]: An error was encountered while trying to flush usage events
